CREATE TABLE `student` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `name` VARCHAR(40) NOT NULL DEFAULT '' COMMENT '名称',
  `age` INT(6) NOT NULL DEFAULT '0' COMMENT '年龄',
  PRIMARY KEY (`id`)
)DEFAULT CHARSET=utf8 COMMENT='学生表'
