package dal.dao.student;

import dal.model.student.StudentDO;
import dal.model.student.StudentDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StudentDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Wed Jan 10 12:17:53 GMT+08:00 2018
     */
    long countByExample(StudentDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Wed Jan 10 12:17:53 GMT+08:00 2018
     */
    int deleteByExample(StudentDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Wed Jan 10 12:17:53 GMT+08:00 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Wed Jan 10 12:17:53 GMT+08:00 2018
     */
    int insert(StudentDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Wed Jan 10 12:17:53 GMT+08:00 2018
     */
    int insertSelective(StudentDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Wed Jan 10 12:17:53 GMT+08:00 2018
     */
    List<StudentDO> selectByExample(StudentDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Wed Jan 10 12:17:53 GMT+08:00 2018
     */
    StudentDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Wed Jan 10 12:17:53 GMT+08:00 2018
     */
    int updateByExampleSelective(@Param("record") StudentDO record, @Param("example") StudentDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Wed Jan 10 12:17:53 GMT+08:00 2018
     */
    int updateByExample(@Param("record") StudentDO record, @Param("example") StudentDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Wed Jan 10 12:17:53 GMT+08:00 2018
     */
    int updateByPrimaryKeySelective(StudentDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Wed Jan 10 12:17:53 GMT+08:00 2018
     */
    int updateByPrimaryKey(StudentDO record);
}